# Generated by Django 4.2.5 on 2023-10-03 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpdate', '0003_images_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='expiring_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='images',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
