# Generated by Django 4.2.5 on 2023-10-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpdate', '0004_images_expiring_link_images_thumbnail_200_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='expiring_link',
        ),
        migrations.RemoveField(
            model_name='images',
            name='thumbnail_200',
        ),
        migrations.RemoveField(
            model_name='images',
            name='thumbnail_400',
        ),
        migrations.RemoveField(
            model_name='images',
            name='upload_time',
        ),
    ]
