# Generated by Django 4.2.5 on 2023-10-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpdate', '0005_remove_images_expiring_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='userprofile',
        ),
    ]
