# Generated by Django 4.2.5 on 2023-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpdate', '0006_remove_images_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_200px',
            field=models.ImageField(blank=True, null=True, upload_to='images/basic/'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_400px',
            field=models.ImageField(blank=True, null=True, upload_to='images/premium/'),
        ),
    ]
