# Generated by Django 4.2.5 on 2023-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpdate', '0010_images_expiration_time_images_temporary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='temporary_image',
            field=models.ImageField(blank=True, null=True, upload_to='temporary_images/'),
        ),
    ]
